name: New issue
description: File a new issue against the Fetch Standard.
body:
  - type: markdown
    attributes:
      value: |
        Before filling out this form, please familiarize yourself with the [Code of Conduct](https://whatwg.org/code-of-conduct). You might also find the [FAQ](https://whatwg.org/faq) and [Working Mode](https://whatwg.org/working-mode) useful.

        If at any point you have questions, please reach out to us on [Chat](https://whatwg.org/chat).
  - type: textarea
    attributes:
      label: "What is the issue with the Fetch Standard?"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thank you for taking the time to improve the Fetch Standard!"
