name: New feature
description: Request a new feature in the Fetch Standard.
labels: ["addition/proposal", "needs implementer interest"]
body:
  - type: markdown
    attributes:
      value: |
        Before filling out this form, please familiarize yourself with the [Code of Conduct](https://whatwg.org/code-of-conduct), [FAQ](https://whatwg.org/faq), and [Working Mode](https://whatwg.org/working-mode). They help with setting expectations and making sure you know what is required. The FAQ ["How should I go about proposing new features to WHATWG standards?"](https://whatwg.org/faq#adding-new-features) is especially relevant.

        If at any point you have questions, please reach out to us on [Chat](https://whatwg.org/chat).
  - type: textarea
    attributes:
      label: "What problem are you trying to solve?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "What solutions exist today?"
  - type: textarea
    attributes:
      label: "How would you solve it?"
  - type: textarea
    attributes:
      label: "Anything else?"
  - type: markdown
    attributes:
      value: "Thank you for taking the time to improve the Fetch Standard!"
