blank_issues_enabled: false
contact_links:
  - name: Chat
    url: https://whatwg.org/chat
    about: Please do reach out with questions and feedback!
  - name: Stack Overflow
    url: https://stackoverflow.com/
    about: If you're having trouble building a web page, this is not the right repository. Consider asking your question on Stack Overflow instead.
